name: scraping2
channels:
  - conda-forge
  - defaults
  - anaconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - et_xmlfile=2.0.0=py311hca03da5_0
  - icu=75.1=hfee45f7_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openpyxl=3.1.5=py311h80987f9_0
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - python=3.11.14=h18782d2_2_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.1
      - beautifulsoup4==4.14.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - executing==2.2.1
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - lxml==6.0.2
      - matplotlib-inline==0.2.1
      - nest-asyncio==1.6.0
      - numpy==2.3.5
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - requests==2.32.5
      - six==1.17.0
      - soupsieve==2.8
      - stack-data==0.6.3
      - tornado==6.5.2
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
prefix: /Users/sjhuskey/miniconda3/envs/scraping2
